name: Build and push to DockerHub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  wine-base:
    name: wine-base docker
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: docker-wine-base
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./wine-base
        file: ./wine-base/Dockerfile
        tags: ekode/docker-wine-base:latest
    
    - name: docker-wine-dotnet 4.0
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./wine-dotnet
        file: ./wine-base/Dockerfile
        tags: |
          ekode/docker-wine-dotnet:latest
          ekode/docker-wine-dotnet:4
    
    - name: docker-wine-dotnet 4.6.2
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./wine-dotnet
        file: ./wine-base/Dockerfile.net462
        tags: ekode/docker-wine-dotnet:462