name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build and push image to Github Packages
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build and push the Docker image
      uses: docker/build-push-action@v1
      with:
        context: .
        file: ./wine-base/Dockerfile
        tags: ekode/docker-wine-base:latest
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com